package pt.rocket.controllers.fragments;


/**
 * Enum used to set the fragment types
 * @author sergiopereira
 *
 */
public enum FragmentType {
    
    UNKNOWN,
    LOGIN,
    REGISTER,
    FORGOT_PASSWORD,
    POPULARITY,
    MAIN_ONE_SLIDE_TEASER,
    PRODUCT_TEASER_LIST,
    CATEGORY_TEASER,
    STATIC_BANNER_TEASER,
    PRODUCT_VARIATION,
    PRODUCT_SHOWOFF,
    PRODUCT_SPECIFICATION,
    PRODUCT_BASIC_INFO,
    CATEGORIES_LEVEL_1,
    CATEGORIES_LEVEL_2,
    CATEGORIES_LEVEL_3,
    HOME,
    SEARCH,
    PRODUCT_LIST,
    PRODUCT_DETAILS, 
    WRITE_REVIEW, 
    REVIEW,
    PRODUCT_DESCRIPTION, 
    PRODUCT_GALLERY, 
    SHOPPING_CART, 
    CHECKOUT_BASKET, 
    CHECKOUT_THANKS, 
    TERMS, 
    MY_ACCOUNT, 
    MY_USER_DATA,
    TRACK_ORDER,
    CHANGE_COUNTRY,
    MY_ADDRESSES,
    CREATE_ADDRESS, 
    EDIT_ADDRESS, 
    SHIPPING_METHODS, 
    PAYMENT_METHODS,
    ABOUT_YOU, 
    MY_ORDER, 
    POLL,
    CHECKOUT_EXTERNAL_PAYMENT, 
    HEADLESS_CART, 
    CAMPAIGNS, 
    EMAIL_NOTIFICATION, 
    NAVIGATION_MENU,
    NAVIGATION_CATEGORIES_LEVEL_1,
    NAVIGATION_CATEGORIES_LEVEL_2,
    NAVIGATION_CATEGORIES_LEVEL_3
}
