package pt.rocket.view.fragments;

public enum FragmentType {

    LOGIN,
    REGISTER,
    FORGOT_PASSWORD,
    POPULARITY,
    MAIN_ONE_SLIDE_TEASER,
    PRODUCT_TEASER_LIST,
    CATEGORY_TEASER,
    STATIC_BANNER_TEASER,
    PRODUCT_VARIATION,
    PRODUCT_SHOWOFF,
    PRODUCT_SPECIFICATION,
    PRODUCT_BASIC_INFO,
    CATEGORIES_LEVEL_1,
    CATEGORIES_LEVEL_2,
    CATEGORIES_LEVEL_3

}
